### ISSUE TITLE
Add error values to apparent magnitude estimates

### ISSUE THREAD

**Issue by djperrefort** [LSSTDESC/SN-PWV#157]
**Issue:** The pipeline output file includes fitted values for the apparent B-band magnitude but does not include an associated error estimate or the relevant covariance values. 

**Thoughts:**
1. @rubind was kind enough to point out the covariance in `mu` should be calculated from full `[mB, x1, c]` covariance matrix as`Cov_mu = [1, alpha, -beta].C.[1, alpha, -beta]`.
1. @rbiswas4 has written some extremely useful code for doing just this sort of thing in [rbiswas4/AnalyzeSN](https://github.com/rbiswas4/AnalyzeSN). With some minor updates in the source (e.g., the `pandas`  dependency has a new API), I was able to get it running successfully on NERSC.

**Proposed Solution:**
Use the code from @rbiswas4 to calculate the covariance matrix from each fit result and add the elements to the output file.

- [x] Extend the `PipelineResult` class to include covariance values (See #162)
  - [x] Add new fields to the dataclass` constructor
  - [x] Modify `PipelineResult.to_csv` to reflect the new output columns. Covariance values should be masked if not provided (to match existing behavior).
- [x]  Port an updated copy of the relevant code from [rbiswas4/AnalyzeSN](https://github.com/rbiswas4/AnalyzeSN) (See #158)
  - [x] Update docs to reflect provenance (See #168)
